### PR TITLE
Update documentation with Home feed visibility for replies

### PR DESCRIPTION
**Pull request by jvns**
I couldn't find any documentation of under what condition my replies are shown in my followers' Home feeds and I noticed a lot of other people are confused about this as well (cf [this post & its replies](https://social.jvns.ca/@b0rk/111890684193270196#.)), so here's a documentation update that explains how it works.

The 3 specific things that I found the most confusing were:

1. A new post you make which starts with an `@mention` is **not** considered a reply (unlike how it works on Twitter)
2. Some other Fediverse software (like maybe Pleroma) will show all your replies on the Home timeline, regardless of whether the follower follows both of the people in the conversation
3. I've often heard that if you want your replies to not be shown on the Home timeline, you need to post them as Unlisted instead of Public. I'm pretty sure that this isn't true (??), but if not it seems like a very common belief.

cc @ClearlyClaire who explained this to me on Mastodon. Please let me know if I got any of this wrong, or if you think it would be better documented somewhere else.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]
Thanks, looks very clear to me!

**Review by andypiper — CHANGES_REQUESTED** [review]
I agree that this is clear and I'm happy to merge, but I would like to request a few small style changes here:

- add a period at the end of each bullet point.
- avoid the use of contractions, particularly in this case please change "it'll" -> "it will". Contractions can be less easy to understand for non-English speakers.

Apart from that, I think this is a great additional clarification.

**Comment by jvns** [comment]
@andypiper done!

**Review by andypiper — APPROVED** [review]
lgtm - thanks for making the suggested changes.

**Pull request merged**
