### PR TITLE
Replace Dart package that was discontinued...

### PR DESCRIPTION
**Pull request by kevmoo**
...with a more actively maintained package

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @rmacd

**Comment by kevmoo** [comment]
Sorry @rmacd ! Maybe @Gargron ?

**Review by Gargron — APPROVED** [review]

**Comment by CodeDoctorDE** [comment]
Why is `mastadon_dart` discontinued?
https://pub.dev/packages/mastodon_dart has a new update 5 days ago

**Comment by kevmoo** [comment]
When I open the PR it was discontinued!

If you look at the package documentation, the last version was updated days
ago.

Yay for having to two things!

**Pull request merged**
