### PR TITLE
Update all Mastodon product screenshots to 4.3

### PR DESCRIPTION
**Pull request by vmstan**
Updates all screenshots for `Using Mastodon` section to 4.3 style.

### CODE REVIEW

**Review by andypiper — APPROVED** [review]
Wow. Thank you so much, this is a wonderful piece of work bringing things up-to-date, nicely-chosen examples as well, appreciate it being kept clear and uncontroversial.

**Comment by andypiper** [comment]
I may leave this for a couple of days before merging while other 4.3 pieces come into place.

**Comment by trwnh** [comment]
I'm wondering if this should be merged as-is or if this would instead be the appropriate time to introduce versioned docs...

**Comment by vmstan** [comment]
The existing screenshots are from 3.0 in many cases. Even if we had multiple versions they wouldn't be these.

**Comment by trwnh** [comment]
I'm saying that the versions would be 3.x and 4.x

**Comment by vmstan** [comment]
There aren't any supported versions of 3.x.

**Comment by renchap** [comment]
We should probably merge this for the release today?

**Pull request merged**
