### PR TITLE
Update security.md (digest, private key, RSASSA-PKCS1-v1_5)

### LINKED ISSUE #1079: HTTP Signatures instructions do not include requirement for digest
The documentation under [security](https://docs.joinmastodon.org/spec/security/) describes that headers `(request-target), host,date)`  are required to be used for signing HTTP requests. However, `digest` seems also to be required (see also comment [here](https://github.com/mastodon/mastodon/discussions/18453#discussioncomment-2783462).

Documentation should be updated to reflect that. Assuming this is correct, there might be other documentation pages like this [blog post](https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/#http-signatures) that require an update too.

### LINKED ISSUE #1080: Misleading instructions for signing the signature string
https://docs.joinmastodon.org/spec/security/ instructs for creating the 'Signature' header:

> The signature string is then hashed with SHA256 and signed with the actor’s public key.

This meant to be the private key not the public key.

> The signature string is then hashed with SHA256 and signed with the actor’s public key.

Speaking for myself, this brought me on the wrong track as it does not mention the need for padding for RSASSA-PKCS1-v1_5. See this [discussion](https://github.com/mastodon/mastodon/discussions/21621).

### PR DESCRIPTION
**Pull request by sventiffe**
Closes #1080
Closes #1079

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
I think the digest part is a bit misleading because the examples are about `GET` requests, which would typically not involve a `Digest` header.

**Comment by sventiffe** [comment]
Fair point. Separated the explanations for digest into a separate section.

Before investing more time, just to clarify: are you generally interested in a contribution? Based on first hands experience I believe the documentation should be fixed (given the growing interest in Mastodon and probably also in the tooling ecosystem) and I am happy to iterate over this PR. But I should have asked earlier.

**Comment by trwnh** [comment]
@sventiffe I just added https://github.com/mastodon/documentation/pull/1060/commits/57d1d7694e09114f53a834a6bc47f2d23cf2db40 to #1060 -- does this commit address your concerns, or are there improvements that could be made in your opinion? To summarize, the examples now include both GET and POST, with the POST example calling out the need for `digest`.

**Comment by sventiffe** [comment]
@trwnh it largely addresses my concerns (your changes/PR are a little bit challenging to navigate as it is really a lot of pending changes bundled into one PR). I left one comment about the error in the doc of signing the string with the public key (it needs to be the private one). 

On a meta level: I am not familiar with the governance structure of this project, the reviewers/approvers and regular contributors. I would however strongly suggest to get documentation improvements out in smaller chunks if that allows faster updates. Given that there are probably a lot of people joining the ecosystem *now*. 🏒 😄 cc @Gargron 

Thank you folks for the hard work! I have no particular feelings about my PR, please close if not needed.

**Comment by trwnh** [comment]
Well, they are small chunks, but they keep building up on account of there being no one to merge them quickly...

**Pull request closed without merging**
