### PR TITLE
Switch hosting to Vercel

### PR DESCRIPTION
**Pull request by renchap**
This follows discussions on Discord about the server load / bandwidth on joinmastodon.org web server.

As the docs are static, they can easily be deployed to Vercel. This will reduce the bandwidth on Mastodon's infrastructure and enable Vercel's optimised delivery on them.

I needed to do the following changes to allow the docs to build on Vercel:
- do not use `.Permalink` for CSS/JS files, they should be relative
- many paths were hardcoded as absolute, they should be relative to allow building in a sub-directory. This is not really needed for Vercel, but is a best practice

### CODE REVIEW

**Comment by renchap** [comment]
There is something wrong with some images on localized pages, for example https://renchap.github.io/mastodon-documentation/zh-cn/

It tries to load `https://renchap.github.io/mastodon-documentation/assets/image%20%289%29.png` which does not exists.

I cant figure out where this file comes from, but it exists on the current docs: https://docs.joinmastodon.org/assets/image%20%289%29.png


Maybe its not generated from Hugo? Or it was from an old generated version but was never purged from the current server?

**Comment by trwnh** [comment]
that's a static asset, it should be in the /static folder

**Comment by renchap** [comment]
> that's a static asset, it should be in the /static folder

Yes, but it does not appear anywhere in the repo, nor in my `public/` directory when I run Hugo. But it exists on the current `docs.joinmastodon.org` server, so it has either been stored there manually, or is a leftover from a previous deployment that was never cleaned up, but is still referenced in some `.md` files (which should not happen)

**Comment by trwnh** [comment]
most likely just a file that didn't get cleaned up, yeah. the translations (or non-en versions) are not well-maintained. i think there was some talk of removing them for being out-of-date, though i'm not sure 100%

**Comment by renchap** [comment]
I updated this PR to use Vercel and not Github Pages, after discussing with @Gargron

It should now build and deploy correctly. The translated images issue is still here, as per my previous comment: https://documentation-git-fork-renchap-master-mastodon.vercel.app/zh-cn/

I think those images should be changed to load the original image, rather this hardcoded filename?

**Review by Gargron — APPROVED** [review]

**Comment by PyGera** [comment]
> This follows discussions on Discord about the server load / bandwidth on joinmastodon.org web server.

Is there a public Discord server of this repository that I can join?

**Pull request merged**
