### PR TITLE
Re-write the instructions for setting up the development environment

### PR DESCRIPTION
**Pull request by jhp0tter**
It shall no longer be under construction!

I can confirm that the updated instructions work on Debian sid as of 2022-11-14.

*Related: mastodon/mastodon#20738*

### CODE REVIEW

**Comment by trwnh** [comment]
just wanted to make you aware of #991 and https://master--tranquil-nougat-d8638a.netlify.app/dev/setup/

**Comment by jhp0tter** [comment]
@trwnh Got it. I'm thinking rebase #1024 on top of #991 by combining my "manual" instructions with your Vagrant instructions?

**Comment by jhp0tter** [comment]
@trwnh Got it, I'll rebase on top of your branch and PR to your repo

**Comment by jhp0tter** [comment]
Closed per request by @trwnh. See #1110

**Pull request closed without merging**
