### PR TITLE
Add pagination - next link for page in parent section

### PR DESCRIPTION
**Pull request by jhauga**
At the bottom of the content added a link to work as pagination for the section.

### CODE REVIEW

**Review by jhauga — COMMENTED** [review]
Matched link formatting as named links appear in documentation.

**Review by jhauga — COMMENTED** [review]
Checked that links match. 

As this seems to be a section that reads in sequential order, thought pagination links would improve page.

**Review by trwnh — CHANGES_REQUESTED** [review]
this shouldn't be done by modifying the content. it should be done by modifying the theme.

**Comment by jhauga** [comment]
> this shouldn't be done by modifying the content. it should be done by modifying the theme.

Ok. I'm gonna close this pull request then and open another one when done.

**Comment by jhauga** [comment]
> this shouldn't be done by modifying the content. it should be done by modifying the theme.

Opened a new pull request https://github.com/mastodon/documentation/pull/1395. This enables sequential navigation on _mostly_ all pages, excluding nested API Method pages in the "API Methods" section.

Working Example:
Also to see a working demo I made a support repo [documentation-sequential-links](https://github.com/jhauga/documentation-sequential-links?tab=readme-ov-file#documentation-sequential-links). It works using "Codespaces". My goto is ` php -S localhost:8000 `. 

To Expand:
Per testing locally - the links successfully updated consistently for me; excluding nested API Method pages mentioned above. I made a support repo with a working example - [documentation-sequential-links](https://github.com/jhauga/documentation-sequential-links?tab=readme-ov-file#documentation-sequential-links). You'll have to use "Codesapces" then localhost it. I used ` php -S localhost:8000 `, GitHub prompts with link, and a working (mostly) example.

With the "Codespaces" localhost, the links in section "API Entities" go to a table-of-contents like page, but this happens when clicking on side nav and clicking on sequential nav built from pull request.

**Pull request closed without merging**
