### PR TITLE
Proposal for adding minimal documentation for undocumented moderation API (webhook)

### PR DESCRIPTION
**Pull request by carrotcypher**
Based off of moderator API functionality added here https://github.com/mastodon/mastodon/pull/18510

It's expected that this draft will need some attention to get details trimmed and accurate, but since it's not documented anywhere else right now it seemed apt to propose it all the same.

### CODE REVIEW

**Comment by vmstan** [comment]
I would like to see them sorted alphabetically, also there are a number of items in the list which don't appear to have Webhooks currently.

```
account.approved
account.created
account.updated
report.created
report.updated
status.created
status.updated

```

**Comment by carrotcypher** [comment]
> I would like to see them sorted alphabetically, also there are a number of items in the list which don't appear to have Webhooks currently.
> 
> ```
> account.approved
> account.created
> account.updated
> report.created
> report.updated
> status.created
> status.updated
> ```

Thanks! Are you saying these aren't available in reality yet? That JSON _(while redacted)_ is from an real raw data of a report though. Should I word it differently to simply say that these are the "codes" that can be returned than calling them available webhooks?

**Comment by vmstan** [comment]
At the moment I don't believe those other webhooks exist, from the current UI:

image

The list in your PR looks reflective of https://github.com/mastodon/mastodon/pull/18510#issuecomment-1151105632 which was a suggestion for additional ones but not currently in the product.

**Comment by carrotcypher** [comment]
> I would like to see them sorted alphabetically

Done!

> also there are a number of items in the list which don't appear to have Webhooks currently.

Fixed based on available selections from UI.

Appreciate the feedback! ❤️

**Comment by vmstan** [comment]
Thank you for the contribution!

**Review by vmstan — APPROVED** [review]

**Review by andypiper — APPROVED** [review]
This is great, thanks for helping and adding these!

**Pull request merged**
